version: "3.9"
services:
  web:
    #image: vulnerables/web-dvwa
    build: .  # указывает на текущую директорию, где лежит Dockerfile
    ports:
      - "8080:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: labdb
      DB_USER: labuser
      DB_PASSWORD: labpass
    depends_on:
      - db
    networks:
      - labnet

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: labdb
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - labnet

volumes:
  db_data:

networks:
  labnet: